<?php

namespace DeividKaiser\CidadesBRCodeigniter\Database\Seeds;

use CodeIgniter\Database\Seeder;

class States extends Seeder
{
    public function run()
    {
        $this->db->table('states')->insertBatch([

            [
                'id' => 1,
                'country_id' => 1,
                'name' => 'Acre',
                'letter' => 'AC',
                'iso' => 12,
                'slug' => 'acre',
                'population' => 816687,
                'lati' => '-8.77',
                'long' => '-70.55',
            ],
            [
                'id' => 2,
                'country_id' => 1,
                'name' => 'Alagoas',
                'letter' => 'AL',
                'iso' => 27,
                'slug' => 'alagoas',
                'population' => 3358963,
                'lati' => '-9.62',
                'long' => '-36.82',
            ],
            [
                'id' => 3,
                'country_id' => 1,
                'name' => 'Amazonas',
                'letter' => 'AM',
                'iso' => 13,
                'slug' => 'amazonas',
                'population' => 4001667,
                'lati' => '-3.47',
                'long' => '-65.1',
            ],
            [
                'id' => 4,
                'country_id' => 1,
                'name' => 'Amapá',
                'letter' => 'AP',
                'iso' => 16,
                'slug' => 'amapa',
                'population' => 782295,
                'lati' => '1.41',
                'long' => '-51.77',
            ],
            [
                'id' => 5,
                'country_id' => 1,
                'name' => 'Bahia',
                'letter' => 'BA',
                'iso' => 29,
                'slug' => 'bahia',
                'population' => 15276566,
                'lati' => '-13.29',
                'long' => '-41.71',
            ],
            [
                'id' => 6,
                'country_id' => 1,
                'name' => 'Ceará',
                'letter' => 'CE',
                'iso' => 23,
                'slug' => 'ceara',
                'population' => 8963663,
                'lati' => '-5.2',
                'long' => '-39.53',
            ],
            [
                'id' => 7,
                'country_id' => 1,
                'name' => 'Distrito Federal',
                'letter' => 'DF',
                'iso' => 53,
                'slug' => 'distrito-federal',
                'population' => 2977216,
                'lati' => '-15.83',
                'long' => '-47.86',
            ],
            [
                'id' => 8,
                'country_id' => 1,
                'name' => 'Espírito Santo',
                'letter' => 'ES',
                'iso' => 32,
                'slug' => 'espirito-santo',
                'population' => 3973697,
                'lati' => '-19.19',
                'long' => '-40.34',
            ],
            [
                'id' => 9,
                'country_id' => 1,
                'name' => 'Goiás',
                'letter' => 'GO',
                'iso' => 52,
                'slug' => 'goias',
                'population' => 6695855,
                'lati' => '-15.98',
                'long' => '-49.86',
            ],
            [
                'id' => 10,
                'country_id' => 1,
                'name' => 'Maranhão',
                'letter' => 'MA',
                'iso' => 21,
                'slug' => 'maranhao',
                'population' => 6954036,
                'lati' => '-5.42',
                'long' => '-45.44',
            ],
            [
                'id' => 11,
                'country_id' => 1,
                'name' => 'Minas Gerais',
                'letter' => 'MG',
                'iso' => 31,
                'slug' => 'minas-gerais',
                'population' => 20997560,
                'lati' => '-18.1',
                'long' => '-44.38',
            ],
            [
                'id' => 12,
                'country_id' => 1,
                'name' => 'Mato Grosso do Sul',
                'letter' => 'MS',
                'iso' => 50,
                'slug' => 'mato-grosso-do-sul',
                'population' => 2682386,
                'lati' => '-20.51',
                'long' => '-54.54',
            ],
            [
                'id' => 13,
                'country_id' => 1,
                'name' => 'Mato Grosso',
                'letter' => 'MT',
                'iso' => 51,
                'slug' => 'mato-grosso',
                'population' => 3305531,
                'lati' => '-12.64',
                'long' => '-55.42',
            ],
            [
                'id' => 14,
                'country_id' => 1,
                'name' => 'Pará',
                'letter' => 'PA',
                'iso' => 15,
                'slug' => 'para',
                'population' => 8272724,
                'lati' => '-3.79',
                'long' => '-52.48',
            ],
            [
                'id' => 15,
                'country_id' => 1,
                'name' => 'Paraiba',
                'letter' => 'PB',
                'iso' => 25,
                'slug' => 'paraiba',
                'population' => 3999415,
                'lati' => '-7.28',
                'long' => '-36.72',
            ],
            [
                'id' => 16,
                'country_id' => 1,
                'name' => 'Pernambuco',
                'letter' => 'PE',
                'iso' => 26,
                'slug' => 'pernambuco',
                'population' => 9410336,
                'lati' => '-8.38',
                'long' => '-37.86',
            ],
            [
                'id' => 17,
                'country_id' => 1,
                'name' => 'Piauí',
                'letter' => 'PI',
                'iso' => 22,
                'slug' => 'piaui',
                'population' => 3212180,
                'lati' => '-6.6',
                'long' => '-42.28',
            ],
            [
                'id' => 18,
                'country_id' => 1,
                'name' => 'Paraná',
                'letter' => 'PR',
                'iso' => 41,
                'slug' => 'parana',
                'population' => 11242720,
                'lati' => '-24.89',
                'long' => '-51.55',
            ],
            [
                'id' => 19,
                'country_id' => 1,
                'name' => 'Rio de Janeiro',
                'letter' => 'RJ',
                'iso' => 33,
                'slug' => 'rio-de-janeiro',
                'population' => 16635996,
                'lati' => '-22.25',
                'long' => '-42.66',
            ],
            [
                'id' => 20,
                'country_id' => 1,
                'name' => 'Rio Grande do Norte',
                'letter' => 'RN',
                'iso' => 24,
                'slug' => 'rio-grande-do-norte',
                'population' => 3474998,
                'lati' => '-5.81',
                'long' => '-36.59',
            ],
            [
                'id' => 21,
                'country_id' => 1,
                'name' => 'Rondônia',
                'letter' => 'RO',
                'iso' => 11,
                'slug' => 'rondonia',
                'population' => 1787279,
                'lati' => '-10.83',
		        'long' => '-63.34',
            ],
            [
                'id' => 22,
                'country_id' => 1,
                'name' => 'Roraima',
                'letter' => 'RR',
                'iso' => 14,
                'slug' => 'roraima',
                'population' => 514229,
                'lati' => '1.99',
                'long' => '-61.33',
            ],
            [
                'id' => 23,
                'country_id' => 1,
                'name' => 'Rio Grande do Sul',
                'letter' => 'RS',
                'iso' => 43,
                'slug' => 'rio-grande-do-sul',
                'population' => 11286500,
                'lati' => '-30.17',
                'long' => '-53.5',
            ],
            [
                'id' => 24,
                'country_id' => 1,
                'name' => 'Santa Catarina',
                'letter' => 'SC',
                'iso' => 42,
                'slug' => 'santa-catarina',
                'population' => 6910553,
                'lati' => '-27.45',
                'long' => '-50.95',
            ],
            [
                'id' => 25,
                'country_id' => 1,
                'name' => 'Sergipe',
                'letter' => 'SE',
                'iso' => 28,
                'slug' => 'sergipe',
                'population' => 2265779,
                'lati' => '-10.57',
                'long' => '-37.45',
            ],
            [
                'id' => 26,
                'country_id' => 1,
                'name' => 'São Paulo',
                'letter' => 'SP',
                'iso' => 35,
                'slug' => 'sao-paulo',
                'population' => 44749699,
                'lati' => '-22.19',
                'long' => '-48.79',
            ],
            [
                'id' => 27,
                'country_id' => 1,
                'name' => 'Tocantins',
                'letter' => 'TO',
                'iso' => 17,
                'slug' => 'tocantins',
                'population' => 1532902,
                'lati' => '-9.46',
                'long' => '-48.26',
            ],
        ]);
    }
}
